### ISSUE TITLE
Display thin vertical lines at indentation (tab) levels, like most code editors

### ISSUE THREAD

**Issue by jimwhitfield** [jaredpetersen/codeprinter#24]
Just to add to the wish list, I'd like to see thin vertical lines at the indentation (tab) levels of my code, like most code editors show these days.   Thanks.  Not holding my breath for this.

**Comment by jaredpetersen** [comment]
Hey - thanks for the feature suggestion.

I'm not sure yet how this would be implemented but it's a good idea. I'm in the middle of modernizing the application - which involves the usage of a slightly different syntax highlighting library - so I'll try to look into it along the way.

**Comment by jaredpetersen** [comment]
Forgot to comment here when I went through some of the refactor work. I looked into it and there didn't seem to be a way to do so easily. I'll add the "Help Wanted" label so that others can start looking into this further.

**Comment by jaredpetersen** [comment]
I just added a feature that includes a vertical line option for line numbers.

It's definitely not at tab levels, but I don't think that's likely to happen unless someone implements that ability into the syntax highlighting library. Additionally, I'm worried that it would clutter the printout.

Going to close this out since this feature is unlikely to ever be added.
